# Generated by Django 4.2.2 on 2023-07-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_employee_dept_alter_employee_desg'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Eid',
            field=models.IntegerField(null=True),
        ),
    ]
