# Generated by Django 4.2.2 on 2023-07-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_employee_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Eid',
            field=models.IntegerField(unique=True),
        ),
    ]
